// Generated by CoffeeScript 1.3.3
var BrothersView,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

_.templateSettings = {
  interpolate: /\{\{(.+?)\}\}/g
};

BrothersView = (function(_super) {

  __extends(BrothersView, _super);

  function BrothersView() {
    return BrothersView.__super__.constructor.apply(this, arguments);
  }

  BrothersView.prototype.initialize = function() {
    var _this = this;
    this.brothers = _.filter(window.brothers, function(b) {
      return b.year === _this.options.year;
    });
    this.template = Handlebars.compile(($('#brother-detail-template')).html());
    return this.render();
  };

  BrothersView.prototype.render = function() {
    return this.$el.html(this.template({
      brothers: this.brothers
    }));
  };

  return BrothersView;

})(Backbone.View);

$(document).ready(function() {
  ($('.carousel')).carousel('pause');
  $('.flexslider').flexslider({
    smoothHeight: true,
    slideshow: false
  });
  return new BrothersView({
    el: '#bro-2012-details',
    year: 2012
  });
});
