window.brothers = [
    // top < 0 moves the image UP within bounded box
    // 2016s
    {
        "aspirations": "To one day become a successful Civil and Environmental Engineer, and help establish a train station in the Middle East that will make transportation between countries faster, cheaper, and more environmentally friendly",
        "course": "15 & 18",
        "hometown": "Beirut, Lebanon",
        "image": "jian_barazi.jpg",
        "interests": "Music, Basketball, Rugby, Women",
        "name": "Jian Barazi",
        "year": 2016,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "Genetic Engineer, Biotech Consultant",
        "course": "20 & 15",
        "hometown": "Ossining, NY",
        "image": "evan_olin.jpg",
        "interests": "Swimming, Music",
        "name": "Evan Olin",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Engineer of Medical Professional, Club Swimming Coach",
        "course": "10",
        "hometown": "Warrington, PA",
        "image": "michael_chen.jpg",
        "interests": "Sports, Food, Music",
        "name": "Michael Chen",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 240
    },
    {
        "aspirations": "To be a physical chemist working either at a research university or for the United States government",
        "course": "5",
        "hometown": "Cherry Hill, NJ",
        "image": "ethan_klein.jpg",
        "interests": "Fine art, Literature, Good organizational skills",
        "name": "Ethan Klein",
        "year": 2016,
        "left": -40,
        "top": -80,
        "zoom": 330
    },
    {
        "aspirations": "To work at a successful computer science company and make a difference in the world.",
        "course": "6",
        "hometown": "San Francisco, CA",
        "image": "pedro_padilla.jpg",
        "interests": "Technical non-fiction, Gardening",
        "name": "Pedro Padilla",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {

        "aspirations": "To be a successful computer graphics programmer.",
        "course": "6",
        "hometown": "Los Altos, CA",
        "image": "itty_belson.jpg",
        "interests": "Programming, Computer Graphics, Videogames.",
        "name": "Itamar Belson",
        "year": 2016,
        "left": 0,
        "top": -30,
        "zoom": 220
    },
    {
        "aspirations": "Use data and math to change the world.",
        "course": "18C",
        "hometown": "Roselle, IL",
        "image": "andrew_hochstead.jpg",
        "interests": "Data, Club DJing, Sand volleyball",
        "name": "Andrew Hochstadt",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "To become a founder of a famous company.",
        "course": "6, 8",
        "hometown": "Vero Beach, FL",
        "image": "paul_coella.jpg",
        "interests": "Lacrosse, DFAC",
        "name": "Paul Coella",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Research energy storage, Startup!",
        "course": "6",
        "hometown": "Wappingers Falls, NY",
        "image": "rob_verkuil.jpg",
        "interests": "Programming, Electronics, Hiking, Cooking, Teaching",
        "name": "Rob Verkuil",
        "year": 2016,
        "left": 0,
        "top": -25,
        "zoom": 220
    },
    {
        "aspirations": "Sustainable Development, Promotion of Innovative Thinking, and other Sound Bites",
        "course": "10",
        "hometown": "New York, New York",
        "image": "qweef_wee.jpg",
        "interests": "Honesty, Bravery, Devotion, Vigor",
        "name": "Githui Maina",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    // 2017s
    {
        "aspirations": "To become the President of the US",
        "course": "16, 17",
        "hometown": "Greenwood Village, CO",
        "image": "brandt_nelson.jpg",
        "interests": "Lacrosse, Politics, Music, Hiking",
        "name": "Brandt Nelson",
        "year": 2017,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Develop a way to extract materials from asteroids, work for NASA, or run a large company",
        "course": "16",
        "hometown": "Luwick, Texas",
        "image": "carlos_cruz.jpg",
        "interests": "Rocket Science, Space Travel, Reading",
        "name": "Carlos Cruz",
        "year": 2017,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "Be a successful entrepeneur",
        "course": "18",
        "hometown": "Orinda, California",
        "image": "matthew_coupin.jpg",
        "interests": "Surfing, Hiking",
        "name": "Matthew Coupin",
        "year": 2017,
        "left": 0,
        "top": -70,
        "zoom": 220
    },
    {
        "aspirations": "To start a successful company and build my brand",
        "course": "2A-6",
        "hometown": "Belmont, Massachusetts",
        "image": "krithi_chandrakasan.jpg",
        "interests": "Baseball, Football",
        "name": "Krithi Chandrakasan",
        "year": 2017,
        "left": 0,
        "top": -50,
        "zoom": 220
    },
    // 2018s
    {
        "aspirations": "Own a tech startup",
        "course": "6-3",
        "hometown": "Scottsdale, Arizona",
        "image": "parker_greene.jpg",
        "interests": "Visual arts, video games",
        "name": "Parker Greene",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220
    },
    {
        "aspirations": "Send people to mars, but make it sound better than that.",
        "course": "16",
        "hometown": "Tampa, Florida",
        "image": "binky.jpg",
        "interests": "Space, School Buses, money, Dylan Joss",
        "name": "Robert Binkowski",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
    {
        "aspirations": "Always be +EV",
        "course": "18",
        "hometown": "Medford, Massachusetts",
        "image": "gaybe.jpg",
        "interests": "Math, Poker, Chess, and The New England Patriots",
        "name": "Gabe Ravel",
        "year": 2018,
        "left": 0,
        "top": -30,
        "zoom": 220   
    },
    {
        "aspirations": "Graduate from MIT, lead/assist in the development of revolutionary medical technology/procedures",
        "course": "6/7",
        "hometown": "Jay, Maine",
        "image": "urk.jpg",
        "interests": "Computational Biology, Music, Soccer, Basketball, Advances in Medical Technology, Cats",
        "name": "Erik Taylor",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
    {
        "aspirations": "Use computer science to revolutionize education",
        "course": "6-3",
        "hometown": "Anaheim, California",
        "image": "dylan_joss.jpg",
        "interests": "Traveling, learning new languages, basketball",
        "name": "Dylan Joss",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
    {
        "aspirations": "Start my own energy or vehicle company",
        "course": "2A-Product Design",
        "hometown": "Rockville Centre, New York",
        "image": "sam_resnique.png",
        "interests": "Restoring muscle cars, surfing, piano, building/construction",
        "name": "Sam Resnick",
        "year": 2018,
        "left": 0,
        "top": -50,
        "zoom": 220   
    },
    {
        "aspirations": "Work with Modular Nuclear Reactor designs and applications",
        "course": "2A-22",
        "hometown": "Mandan, North Dakota",
        "image": "sam_ravnaas.jpg",
        "interests": "Pole Vault, guitar, concerts, building stuff",
        "name": "Sam Ravnaas",
        "year": 2018,
        "left": 0,
        "top": 0,
        "zoom": 220   
    },
    {
        "aspirations": "To make money, have fun, and live a dope life",
        "course": "3 with a minor in 2",
        "hometown": "Bainbridge Island, WA",
        "image": "alex_derry.jpg",
        "interests": "Rowing",
        "name": "Alex Derry",
        "year": 2018,
        "left": 0,
        "top": 0,
        "zoom": 220   
    },
    {
        "aspirations": "Being ridiculously rich",
        "course": "6 and 15",
        "hometown": "Beirut, Lebanon",
        "image": "tarek_mansour.jpg",
        "interests": "Skiing and soccer",
        "name": "Tarek Mansour",
        "year": 2018,
        "left": 0,
        "top": -40,
        "zoom": 220   
    },
    {
        "aspirations": "Play in the NFL",
        "course": "6",
        "hometown": "Toronto, Canada",
        "image": "manjot_sangha.png",
        "interests": "Being Canadian",
        "name": "Manjot Sangha",
        "year": 2018,
        "left": 0,
        "top": 0,
        "zoom": 220   
    },
    {
        "aspirations": "Get rich or die trying",
        "course": "2",
        "hometown": "New York City, New York",
        "image": "greg_cartagena.jpg",
        "interests": "Basketball",
        "name": "Greg Cartagena",
        "year": 2018,
        "left": 0,
        "top": -40,
        "zoom": 220   
    },
];
