window.brothers = [
    {
        "aspirations": "Bain and Co. Consulting, Stanford Med", 
        "course": "20", 
        "hometown": "Yorktown, VA", 
        "image": "nick_swenson.jpg", 
        "interests": "Golf, P. Diddy", 
        "name": "Nick Swenson", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Trading", 
        "course": "8", 
        "hometown": "Rancho Cucamunga", 
        "image": "josh_goodwill.jpg", 
        "interests": "Electro, Trance, Concerts", 
        "name": "Joshua Leonard-Goodwill", 
        "year": 2012,
        "left": 0,
        "top": -50,
        "zoom": 220
    }, 
    {
        "aspirations": "Tesla Motors Engineer", 
        "course": "2", 
        "hometown": "Fresno, CA", 
        "image": "adam_delton.jpg", 
        "interests": "Electro, Dubstep, DJing", 
        "name": "Adam Delton", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Bain and Co. Consulting, Private Equity", 
        "course": "8, 18", 
        "hometown": "San Diego, CA", 
        "image": "stephen_goodman.jpg", 
        "interests": "Lead-Singer of Transit Gloria", 
        "name": "Stephen Goodman", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Rest Devices Startup", 
        "course": "2", 
        "hometown": "Newton, MA", 
        "image": "chao_he.jpg", 
        "interests": "Diving, Swimming, Krillin", 
        "name": "Chao He", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Biomedical Engineering", 
        "course": "20", 
        "hometown": "Anchorage, AK", 
        "image": "colin_reisterer.jpg", 
        "interests": "Snowboarding, Cycling", 
        "name": "Colin Reisterer", 
        "year": 2012,
        "left": -80,
        "top": 0,
        "zoom": 300
    }, 
    {
        "aspirations": "Pelton & Crane Engineer", 
        "course": "2", 
        "hometown": "Charlotte, NC", 
        "image": "michael_bickers.jpg", 
        "interests": "Lacrosse, Golf", 
        "name": "Michael Bickers", 
        "year": 2012,
        "left": -75,
        "top": -95,
        "zoom": 300
    },
    {
        "aspirations": "Quora, Facebook developer", 
        "course": "6", 
        "hometown": "Boston, MA", 
        "image": "neel_hajare.jpg", 
        "interests": "Coding, Developing", 
        "name": "Neel Hajare", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 240
    }, 
    {
        "aspirations": "Multi-national charity organization", 
        "course": "2", 
        "hometown": "Omaha, NE", 
        "image": "hank_peepee.jpg", 
        "interests": "Wrestling, Live music, Donating to Locks of Love", 
        "name": "Hank Peppe", 
        "year": 2012,
        "left": 0,
        "top": -40,
        "zoom": 220
    }, 
    {
        "aspirations": "Risk Management Banking at Bank of America", 
        "course": "14", 
        "hometown": "Philadelphia, PA", 
        "image": "trace_sauter.jpg", 
        "interests": "Bowties, cycling, swimming, and economics", 
        "name": "Trace Sauter", 
        "year": 2012,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Materials Selection & Product Development", 
        "course": "3", 
        "hometown": "Woodbury, NY", 
        "image": "brian_wee.jpg", 
        "interests": "Kinesiology, A Cappella, Tennis", 
        "name": "Brian Wee", 
        "year": 2012,
        "left": -20,
        "top": 0,
        "zoom": 280
    }, 
    {
        "aspirations": "SpaceX", 
        "course": "16", 
        "hometown": "Corpus Christi, TX", 
        "image": "jason_elizalde.jpg", 
        "interests": "Ice cream, EDM, Concerts", 
        "name": "Jason Elizalde", 
        "year": 2013,
        "left": 0,
        "top": -65,
        "zoom": 220
    }, 
    {
        "aspirations": "Google, or Startup", 
        "course": "6", 
        "hometown": "Grand Rapids, MO", 
        "image": "pat_marx.jpg", 
        "interests": "Electro", 
        "name": "Pat Marx", 
        "year": 2013,
        "left": 0,
        "top": -40,
        "zoom": 220
    }, 
    {
        "aspirations": "Software", 
        "course": "6", 
        "hometown": "Sacramento, CA", 
        "image": "albert_rodenius.jpg", 
        "interests": "EDM, Technology", 
        "name": "Albert Rodenius", 
        "year": 2013,
        "left": -25,
        "top": -50,
        "zoom": 360
    }, 
    {
        "aspirations": "Research", 
        "course": "3", 
        "hometown": "Las Vegas, NV", 
        "image": "charles_huang.jpg", 
        "interests": "EDM, Concerts, Philosophy", 
        "name": "Charles Huang", 
        "year": 2013,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Alternative energy", 
        "course": "10", 
        "hometown": "Amherst, MA", 
        "image": "scott_jenkins.jpg", 
        "interests": "Soccer, MIT Energy Club,", 
        "name": "Scott Jenkins", 
        "year": 2013,
        "left": 0,
        "top": -20,
        "zoom": 220
    }, 
    {
        "aspirations": "Web developer", 
        "course": "6", 
        "hometown": "Jacksonville, FL", 
        "image": "george_erickson.jpg", 
        "interests": "Web developing, Sriracha sauce", 
        "name": "George Erickson", 
        "year": 2013,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "SpaceX, build/design machines that go really fast", 
        "course": "2", 
        "hometown": "Miami, FL", 
        "image": "alex_teuffer.jpg", 
        "interests": "LA disco, French electro, German techno, British rock, info art", 
        "name": "Alex Teuffer Pando", 
        "year": 2013,
        "left": 0,
        "top": -25,
        "zoom": 220
    }, 
    {
        "aspirations": "To become the next Queen", 
        "course": "8", 
        "hometown": "London, UK", 
        "image": "jack_newman.jpg", 
        "interests": "Being British, Mate", 
        "name": "Jack Newman", 
        "year": 2013,
        "left": 0,
        "top": -100,
        "zoom": 220
    }, 
    {
        "aspirations": "Alternative Energy", 
        "course": "2", 
        "hometown": "San Diego, CA", 
        "image": "jackson_crane.jpg", 
        "interests": "Fencing, Traveling", 
        "name": "Jackson Crane", 
        "year": 2013,
        "left": 0,
        "top": -80,
        "zoom": 220
    }, 
    {
        "aspirations": "Raytheon Engineer", 
        "course": "6", 
        "hometown": "Boston, MA", 
        "image": "david_benhaim.jpg", 
        "interests": "Robots, Rock", 
        "name": "David Benhaim", 
        "year": 2013,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Goldman Sachs, PhD in physics", 
        "course": "8", 
        "hometown": "Colorado Springs, CO", 
        "image": "chris_schuch.jpg", 
        "interests": "Indie music, Physics, Travel", 
        "name": "Christopher Schuch", 
        "year": 2013,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Management consultant for the music industry",
        "course": "15",
        "hometown": "San Diego, CA",
        "image": "chas_stahl.jpg",
        "interests": "Rap music, Writing lyrics, Baseball, Dance, Networking, Business",
        "name": "Chas Stahl",
        "year": 2013,
        "left": 0,
        "top": -50,
        "zoom": 220
    },
    {
        "aspirations": "Materials research", 
        "course": "3", 
        "hometown": "Rochester, NY", 
        "image": "max_powers.jpg", 
        "interests": "Football, Sign language, History", 
        "name": "Max Powers", 
        "year": 2014,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Saving the world", 
        "course": "6", 
        "hometown": "New York City", 
        "image": "charlie_gordon.jpg", 
        "interests": "Computers, Open source software, Politics, Soccer", 
        "name": "Charlie Gordon", 
        "year": 2014,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Chemical Engineering, Pharmaceutical Engineering", 
        "course": "10", 
        "hometown": "Potomac, MD", 
        "image": "kevin_clayton.jpg", 
        "interests": "Football, Music", 
        "name": "Kevin Clayton", 
        "year": 2014,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "NASA", 
        "course": "2", 
        "hometown": "Pasadena, CA", 
        "image": "rick_zang.jpg", 
        "interests": "Indie-rock, Hipster stuff", 
        "name": "Rick Zang", 
        "year": 2014,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Materials Engineering, Start a company", 
        "course": "3", 
        "hometown": "Rye, NY", 
        "image": "mac_gager.jpg", 
        "interests": "Track, Renewable Energy, Outdoorsy stuff", 
        "name": "Mac Gager", 
        "year": 2014,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Management Consulting, Venture capitalism, Be a live audience member at SNL", 
        "course": "14, 15", 
        "hometown": "San Diego, CA", 
        "image": "zev_bimstein.jpg", 
        "interests": "Magnets, Playing night crawlers, Skitchin\u2019", 
        "name": "Zev Bimstein", 
        "year": 2015,
        "left": 0,
        "top": -60,
        "zoom": 220
    }, 
    {
        "aspirations": "Carbon nano-tube engineering", 
        "course": "3", 
        "hometown": "Lake Tahoe, CA", 
        "image": "mikey_suglian.jpg", 
        "interests": "Skiing, EDM", 
        "name": "Mikey Suglian", 
        "year": 2015,
        "left": 0,
        "top": -36,
        "zoom": 220
    }, 
    {
        "aspirations": "Materials Engineer", 
        "course": "3", 
        "hometown": "Lexington, MA", 
        "image": "jasper_lienhard.jpg", 
        "interests": "EDM, Piano", 
        "name": "Jasper Lienhard", 
        "year": 2015,
        "left": 0,
        "top": -10,
        "zoom": 220
    }, 
    {
        "aspirations": "Coder for Apple", 
        "course": "6", 
        "hometown": "Dallas, TX", 
        "image": "chris_kim.jpg", 
        "interests": "Crew, Coding", 
        "name": "Chris Kim", 
        "year": 2015,
        "left": 0,
        "top": 0,
        "zoom": 220
    }, 
    {
        "aspirations": "Trading, Aerospace Engineering", 
        "course": "16", 
        "hometown": "San Diego, CA", 
        "image": "brandon_le.jpg", 
        "interests": "EDM, Bodyboarding, Photography, Art", 
        "name": "Brandon Le", 
        "year": 2015,
        "left": 0,
        "top": 0,
        "zoom": 240
    }, 
    {
        "aspirations": "Nuclear engineering", 
        "course": "2", 
        "hometown": "Potomac, MD", 
        "image": "thomas_finn.jpg", 
        "interests": "Swimming, cave-dwelling", 
        "name": "Thomas Finn", 
        "year": 2015,
        "left": 0,
        "top": -40,
        "zoom": 220
    }, 
    {
        "aspirations": "To design a new, more practical, and safer vehicles", 
        "course": "2", 
        "hometown": "Colorado Springs, CO", 
        "image": "parker_chambers.jpg", 
        "interests": "Intervarsity, long boarding, concept cars, graffiti, and extreme sports", 
        "name": "Parker Chambers", 
        "year": 2015,
        "left": 0,
        "top": -10,
        "zoom": 220
    },
    {
        "aspirations": "Mechanical Engineering, Engine Design",
        "course": "?",
        "hometown": "De Soto, MO",
        "image": "jared_mckeon.jpg",
        "interests": "Piano, Guitar, Video Games",
        "name": "Jared McKeon",
        "year": 2016,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "To one day become a successful Civil and Environmental Engineer, and help establish a train station in the Middle East that will make transportation between countries faster, cheaper, and more environmentally friendly",
        "course": "?",
        "hometown": "Beirut, Lebanon",
        "image": "jian_barazi.jpg",
        "interests": "Music, Basketball, Rugby, Women",
        "name": "Jian Barazi",
        "year": 2016,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "Genetic Engineer, Bioengeering",
        "course": "?",
        "hometown": "Ossining, NY",
        "image": "evan_olin.jpg",
        "interests": "Swimming, Music",
        "name": "Evan Olin",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Engineer of Medical Professional, Club Swimming Coach",
        "course": "?",
        "hometown": "Warrington, PA",
        "image": "michael_chen.jpg",
        "interests": "Sports, Food, Music",
        "name": "Michael Chen",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 240
    }
];
