window.brothers = [
    // 2015s
    // top < 0 moves the image UP within bounded box
    {
        "aspirations": "Saving the world", 
        "course": "6", 
        "hometown": "New York City", 
        "image": "charlie_gordon.jpg", 
        "interests": "Computers, Open source software, Politics, Soccer", 
        "name": "Charlie Gordon", 
        "year": 2015,
        "left": 0,
        "top": 0,
        "zoom": 240
    }, 
    {
        "aspirations": "Management Consulting, Venture capitalism, Be a live audience member at SNL", 
        "course": "14, 15", 
        "hometown": "San Diego, CA", 
        "image": "zev_bimstein.jpg", 
        "interests": "Magnets, Playing night crawlers, Skitchin\u2019", 
        "name": "Zev Bimstein", 
        "year": 2015,
        "left": 0,
        "top": -60,
        "zoom": 220
    }, 
    {
        "aspirations": "Carbon nano-tube engineering", 
        "course": "3", 
        "hometown": "Lake Tahoe, CA", 
        "image": "mikey_suglian.jpg", 
        "interests": "Skiing, EDM", 
        "name": "Mikey Suglian", 
        "year": 2015,
        "left": 0,
        "top": -36,
        "zoom": 220
    }, 
    {
        "aspirations": "Materials Engineer", 
        "course": "3", 
        "hometown": "Lexington, MA", 
        "image": "jasper_lienhard.jpg", 
        "interests": "EDM, Piano", 
        "name": "Jasper Lienhard", 
        "year": 2015,
        "left": 0,
        "top": -10,
        "zoom": 220
    }, 
    {
        "aspirations": "Coder for Apple", 
        "course": "6", 
        "hometown": "Dallas, TX", 
        "image": "chris_kim.jpg", 
        "interests": "Crew, Coding", 
        "name": "Chris Kim", 
        "year": 2015,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Nuclear engineering", 
        "course": "6", 
        "hometown": "Potomac, MD", 
        "image": "thomas_finn.jpg", 
        "interests": "Swimming, cave-dwelling", 
        "name": "Thomas Finn", 
        "year": 2015,
        "left": 0,
        "top": -40,
        "zoom": 220
    }, 
    {
        "aspirations": "To design a new, more practical, and safer vehicles", 
        "course": "2", 
        "hometown": "Colorado Springs, CO", 
        "image": "parker_chambers.jpg", 
        "interests": "Intervarsity, long boarding, concept cars, graffiti, and extreme sports", 
        "name": "Parker Chambers", 
        "year": 2015,
        "left": 0,
        "top": -10,
        "zoom": 220
    },
    // 2016s
    {
        "aspirations": "To one day become a successful Civil and Environmental Engineer, and help establish a train station in the Middle East that will make transportation between countries faster, cheaper, and more environmentally friendly",
        "course": "15 & 18",
        "hometown": "Beirut, Lebanon",
        "image": "jian_barazi.jpg",
        "interests": "Music, Basketball, Rugby, Women",
        "name": "Jian Barazi",
        "year": 2016,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "Genetic Engineer, Biotech Consultant",
        "course": "20 & 15",
        "hometown": "Ossining, NY",
        "image": "evan_olin.jpg",
        "interests": "Swimming, Music",
        "name": "Evan Olin",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Engineer of Medical Professional, Club Swimming Coach",
        "course": "10",
        "hometown": "Warrington, PA",
        "image": "michael_chen.jpg",
        "interests": "Sports, Food, Music",
        "name": "Michael Chen",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 240
    },
    {
        "aspirations": "To be a physical chemist working either at a research university or for the United States government",
        "course": "5",
        "hometown": "Cherry Hill, NJ",
        "image": "ethan_klein.jpg",
        "interests": "Fine art, Literature, Good organizational skills",
        "name": "Ethan Klein",
        "year": 2016,
        "left": -40,
        "top": -80,
        "zoom": 330
    },
    {
        "aspirations": "To make computers think like us.",
        "course": "6 & 9",
        "hometown": "Baltimore, MD",
        "image": "g_gomez.jpg",
        "interests": "Programming, Music, DJing, Soccer",
        "name": "Gerardo Gomez",
        "year": 2016,
        "left": 0,
        "top": -20,
        "zoom": 290
    },
    {
        "aspirations": "To work at a successful computer science company and make a difference in the world.",
        "course": "6",
        "hometown": "San Francisco, CA",
        "image": "pedro_padilla.jpg",
        "interests": "Technical non-fiction, Gardening",
        "name": "Pedro Padilla",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {

        "aspirations": "To be a successful computer graphics programmer.",
        "course": "6",
        "hometown": "Los Altos, CA",
        "image": "itty_belson.jpg",
        "interests": "Programming, Computer Graphics, Videogames.",
        "name": "Itamar Belson",
        "year": 2016,
        "left": 0,
        "top": -30,
        "zoom": 220
    },
    {
        "aspirations": "Programming, Becoming a famous DJ.",
        "course": "6",
        "hometown": "Roselle, IL",
        "image": "andrew_hochstead.jpg",
        "interests": "Club DJ, Volleyball",
        "name": "Andrew Hochstadt",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "To become a founder of a famous company.",
        "course": "6, 8",
        "hometown": "Vero Beach, FL",
        "image": "paul_coella.jpg",
        "interests": "Lacrosse, DFAC",
        "name": "Paul Coella",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "Research energy storage, Startup!",
        "course": "6",
        "hometown": "Wappingers Falls, NY",
        "image": "rob_verkuil.jpg",
        "interests": "Programming, Electronics, Hiking, Cooking, Teaching",
        "name": "Rob Verkuil",
        "year": 2016,
        "left": 0,
        "top": -25,
        "zoom": 220
    },
    {
        "aspirations": "Sustainable Development, Promotion of Innovative Thinking, and other Sound Bites",
        "course": "10",
        "hometown": "New York, New York",
        "image": "qweef_wee.jpg",
        "interests": "Honesty, Bravery, Devotion, Vigor",
        "name": "Githui Maina",
        "year": 2016,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    // 2017s
    {
        "aspirations": "Get rich or die trying",
        "course": "2",
        "hometown": "Hong Kong",
        "image": "anant_kappor.jpg",
        "interests": "Robotics, Kickboxing, Scuba Diving",
        "name": "Anant Kapoor",
        "year": 2017,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "To become the President of the US",
        "course": "16, 17",
        "hometown": "Greenwood Village, CO",
        "image": "brandt_nelson.jpg",
        "interests": "Lacrosse, Politics, Music, Hiking",
        "name": "Brandt Nelson",
        "year": 2017,
        "left": 0,
        "top": 0,
        "zoom": 220
    },
    {
        "aspirations": "To work in a major pharmaceutical company synthesizing new medicine for an ever-changing world",
        "course": "10B",
        "hometown": "Silver Spring, Maryland",
        "image": "orlando_arevalo.jpg",
        "interests": "Traveling, Paintballing, Ice Hockey, Hanging out",
        "name": "Orlando Arevalo",
        "year": 2017,
        "left": 0,
        "top": -30,
        "zoom": 220
    },
    {
        "aspirations": "Develop a way to extract materials from asteroids, work for NASA, or run a large company",
        "course": "16",
        "hometown": "Luwick, Texas",
        "image": "carlos_cruz.jpg",
        "interests": "Rocket Science, Space Travel, Reading",
        "name": "Carlos Cruz",
        "year": 2017,
        "left": 0,
        "top": -40,
        "zoom": 220
    },
    {
        "aspirations": "Be a successful entrepeneur",
        "course": "18",
        "hometown": "Orinda, California",
        "image": "matthew_coupin.jpg",
        "interests": "Surfing, Hiking",
        "name": "Matthew Coupin",
        "year": 2017,
        "left": 0,
        "top": -70,
        "zoom": 220
    },
    {
        "aspirations": "To start a successful company and build my brand",
        "course": "2A-6",
        "hometown": "Belmont, Massachusetts",
        "image": "krithi_chandrakasan.jpg",
        "interests": "Baseball, Football",
        "name": "Krithi Chandrakasan",
        "year": 2017,
        "left": 0,
        "top": -50,
        "zoom": 220
    },
    // 2018s
    {
        "aspirations": "Own a tech startup",
        "course": "6-3",
        "hometown": "Scottsdale, Arizona",
        "image": "parker_greene.jpg",
        "interests": "Visual arts, video games",
        "name": "Parker Greene",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220
    },
    {
        "aspirations": "Send people to mars, but make it sound better than that.",
        "course": "16",
        "hometown": "Tampa, Florida",
        "image": "binky.jpg",
        "interests": "Space, School Buses, money, Dylan Joss",
        "name": "Robert Binkowski",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
    {
        "aspirations": "Always be +EV",
        "course": "18",
        "hometown": "Medford, Massachusetts",
        "image": "gaybe.jpg",
        "interests": "Math, Poker, Chess, and The New England Patriots",
        "name": "Gabe Ravel",
        "year": 2018,
        "left": 0,
        "top": -30,
        "zoom": 220   
    },
    {
        "aspirations": "Graduate from MIT, lead/assist in the development of revolutionary medical technology/procedures",
        "course": "6/7",
        "hometown": "Jay, Maine",
        "image": "urk.jpg",
        "interests": "Computational Biology, Music, Soccer, Basketball, Advances in Medical Technology, Cats",
        "name": "Erik Taylor",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
    {
        "aspirations": "Use computer science to revolutionize education",
        "course": "6-3",
        "hometown": "Anaheim, California",
        "image": "dylan_joss.jpg",
        "interests": "Traveling, learning new languages, basketball",
        "name": "Dylan Joss",
        "year": 2018,
        "left": 0,
        "top": -20,
        "zoom": 220   
    },
];
